# Generated by Django 5.1.3 on 2024-12-05 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('film_title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=100)),
                ('year_of_release', models.PositiveIntegerField(default=1888)),
                ('personal_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MaxValueValidator(5.0)])),
                ('review', models.TextField(default='No review provided')),
                ('would_recommend', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
