# Generated by Django 5.1.3 on 2024-12-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_filmlog_would_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmlog',
            name='I_have_seen_this_film_before',
            field=models.BooleanField(default=False),
        ),
    ]
